# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tpetit <tpetit@student.s19.be>             +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/11/30 12:26:52 by tpetit            #+#    #+#              #
#    Updated: 2022/02/08 16:07:11 by tpetit           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CPPFLAGS = -g

SRCS = main.cpp AMateria.cpp Character.cpp Cure.cpp Ice.cpp MateriaSource.cpp

NAME = abstract_class

all:
	g++ $(CPPFLAGS) $(SRCS) -o $(NAME)
	
clean:
	rm $(NAME)