# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tpetit <tpetit@student.s19.be>             +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/10/26 09:48:28 by tpetit            #+#    #+#              #
#    Updated: 2022/02/28 11:06:58 by tpetit           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CPPFLAGS = -Wall -Wextra -Werror

SRCS = main.cpp

NAME = hiThisIsBrain

all:
	c++ $(CPPFLAGS) $(SRCS) -o $(NAME)
	
clean:
	rm $(NAME)
