# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tpetit <tpetit@student.s19.be>             +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/10/26 09:11:27 by tpetit            #+#    #+#              #
#    Updated: 2022/02/26 12:54:00 by tpetit           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CPPFLAGS = -fpermissive

SRCS = main.cpp

NAME = some_functions

all:
	g++ $(CPPFLAGS) $(SRCS) -o $(NAME)
	
clean:
	rm $(NAME)
