# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tpetit <tpetit@student.s19.be>             +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/10/26 15:26:31 by tpetit            #+#    #+#              #
#    Updated: 2021/10/26 15:51:33 by tpetit           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CPPFLAGS = 

SRCS = main.cpp Karen.cpp

NAME = karenFilter

all:
	g++ $(CPPFLAGS) $(SRCS) -o $(NAME)
	
clean:
	rm $(NAME)