# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tpetit <tpetit@student.s19.be>             +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/10/21 11:02:55 by tpetit            #+#    #+#              #
#    Updated: 2022/03/01 10:33:01 by tpetit           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CPPFLAGS = -Wall -Wextra -Werror

all:
	c++ $(CPPFLAGS) Contact.cpp PhoneBook.cpp main.cpp -o phone_book
	
clean:
	rm phone_book
