# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tpetit <tpetit@student.s19.be>             +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/11/30 12:26:52 by tpetit            #+#    #+#              #
#    Updated: 2021/11/30 14:24:06 by tpetit           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CPPFLAGS = 

SRCS = main.cpp Animal.cpp Cat.cpp Dog.cpp Brain.cpp

NAME = abstract_class

all:
	g++ $(CPPFLAGS) $(SRCS) -o $(NAME)
	
clean:
	rm $(NAME)