# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tpetit <tpetit@student.s19.be>             +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/11/30 12:26:52 by tpetit            #+#    #+#              #
#    Updated: 2022/02/28 11:06:58 by tpetit           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CPPFLAGS = 

SRCS = main.cpp Animal.cpp Cat.cpp Dog.cpp WrongAnimal.cpp WrongCat.cpp

NAME = abstract_class

all:
	c++ $(CPPFLAGS) $(SRCS) -o $(NAME)
	
clean:
	rm $(NAME)